name: stay_home_polls_app
description: Stay Home Polls App

version: 0.1.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  async: ^2.4.2
  cloud_firestore: ^0.13.5
  cupertino_icons: ^0.1.2
  firebase_auth: ^0.15.3+1
  google_fonts: ^1.1.0
  pedantic: ^1.9.2
  percent_indicator: ^2.1.1
  provider: ^4.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.7.3"

flutter:
  uses-material-design: true
  assets:
    - assets/icons/

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path_ios: "assets/icons/ios_icon.png"
  image_path_android: "assets/icons/android_icon.png"
