name: Flutter CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  analyze:
    name: Analyze
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          channel: dev

      - run: flutter analyze --fatal-infos
    # - run: flutter test


  ios-build:
    name: iOS build
    runs-on: macos-latest
    needs: [analyze]

    steps:
    - uses: actions/checkout@v2
    - uses: subosito/flutter-action@v1
      with:
        channel: dev

    - run: flutter pub get
    - run: flutter build ios --release --no-codesign

   # - uses: actions/upload-artifact@v1
   #   with:
   #     name: ios_release
   #     path: build/ios/iphoneos/Runner.app


  android-build:
    name: Android build
    runs-on: ubuntu-latest
    needs: [analyze]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
        with:
          channel: dev

      - run: flutter pub get
      - run: flutter build apk

     # - uses: actions/upload-artifact@v1
     #   with:
     #     name: android_release
     #     path: build/app/outputs/flutter-apk/app-release.apk
